#!/bin/bash

# Define column headers
printf "%-10s %-5s %-5s %-8s %-8s %-5s %-10s %-5s %-10s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "COMMAND"

# Use the ps command to list processes in a user-oriented format
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --sort=-%cpu | head -50
