#!/bin/bash

# Check for the command-line argument
case "$1" in
  start|stop|restart)
    sudo ./manage_my_process "$1"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
