#!/bin/bash

# Function to handle SIGTERM signal
handle_sigterm() {
  echo "I am invincible!!!"
  exit 0
}

# Set up a trap to catch the SIGTERM signal
trap 'handle_sigterm' SIGTERM

# Main loop
while true; do
  echo "To infinity and beyond"
  sleep 2
done
